### ISSUE TITLE
[PROPOSAL] "Search" function in SatCom.

### ISSUE THREAD

**Issue by Quartofel** [colobot/colobot#884] opened 2016-12-30 14:14 UTC
I think that it'd be really useful feature. Instead of digging through growing pile of informaton player could simply search what he needs with keywords. Scrolling through everything can be annoying. I don't know how hard it'd be to implement tough.

**Comment by krzys-h** [comment] 2016-12-30 14:18
Duplicate of #276

**Closed by krzys-h** 2016-12-30 14:18 UTC
