### ISSUE TITLE
Text shifting by x coordinate on help screen.

### ISSUE THREAD

**Issue by X64E** [colobot/colobot#1474] opened 2021-11-30 12:18 UTC
This is clearly visible if you change the font size.

![CBOT](https://user-images.githubusercontent.com/95232774/144045312-a61ce104-05f5-4b23-9961-a7292bd533d8.gif)

If font big text shifted to right side:

![74](https://user-images.githubusercontent.com/95232774/144045851-9a4e8cdd-6b34-4c94-8f8c-4eca6d6e83db.png)

if font small text shifted to left side. And goes beyond the frame:

![33](https://user-images.githubusercontent.com/95232774/144045987-b8a0c758-68ad-4e82-a08a-05a6338b6662.png)

**Comment by MrSimbax** [comment] 2021-11-30 16:52
Duplicate of #1463, closing.

**Closed by MrSimbax** 2021-11-30 16:52 UTC
Labels: duplicate
