### ISSUE TITLE
Random pixelated fonts 

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#738] opened 2016-03-20 15:17 UTC
After few changes in font rendering engine, some text looks worse than before in some resolutions.

Few examples:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/13905138/006afb02-eeb7-11e5-95ab-73d8c5902458.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/13905139/070d3b8c-eeb7-11e5-863a-aacd6b7e960b.png)
![schowek03](https://cloud.githubusercontent.com/assets/4019345/13905143/17642248-eeb7-11e5-96bd-e0d8b807c86c.png)

**Comment by krzys-h** [comment] 2016-03-20 15:21
Define 'some resolutions'. I don't seem to be able to reproduce this.

**Comment by RaptorParkowsky** [comment] 2016-03-20 15:33
First two are default 800x600 windowed screen mode. The third screenshot is also default 800x600, but I maximized the window while I was in main menu before I started any level.

**Comment by krzys-h** [comment] 2016-03-20 15:56
I tried the exact same resolutions and couldn't reproduce this. Maybe show your graphics settings?

**Comment by RaptorParkowsky** [comment] 2016-03-20 16:15
Well, I tested with some graphic settings - it doesn't really depends on texture filtering, MSAA, etc. Experimenting with window size helps to fix readable of some words, but starting with default settings there's still some places that text is messed up.

**Comment by RaptorParkowsky** [comment] 2016-03-20 17:34
It also have nothing to do with the game's UI language. I changed the language, restarted the game and still the "Missions" button is messed up in 800x600 window from very beginning.

I guess it's something wrong with refreshing text resolution in few places, because most of the text is looking good in any resolution.

**Comment by piotrdz** [comment] 2016-03-21 09:25
@RaptorParkowsky: can you check if this issue occurred before my commit 8baccb0? It's possible that I broke something when optimizing texture generation in text rendering.

**Comment by krzys-h** [comment] 2016-03-21 10:07
@piotrdz: He already said that this occurs since text rendering changes

**Comment by RaptorParkowsky** [comment] 2016-03-21 10:16
@piotrdz Yeah, I can confirm that occured after your fixes. I also remember that "Missions" button in main menu even long before that commit was a little strange, but possibly this is more related to UI though.

This is how it was looking before on standard 800x600 window:
![schowek03](https://cloud.githubusercontent.com/assets/4019345/13915552/c2f6f02e-ef55-11e5-88bf-7da66c160ba3.png)
A little bit strange, but still readable. The new one that's in latest dev build is almost completely unreadable in standard 800x600 window.

**Comment by piotrdz** [comment] 2016-03-21 11:25
@RaptorParkowsky: Just like @krzys_h, I can't reproduce it on my machine. I'll look over my code later and see what could be causing this.

**Comment by krzys-h** [comment] 2016-03-21 19:57
I just got some similar text rendering artifacts after resizing window from 1280x1024 to 800x600 while having mission 1.3 loaded. Those are most visible on the black background of the debug stats, but if you look closely you can see them in other places too.
![image](https://cloud.githubusercontent.com/assets/1517255/13932208/4e04007a-efa7-11e5-9d8f-171158984ff6.png)

**Comment by piotrdz** [comment] 2016-03-22 10:37
Please check if my last commit fixes this problem.If it still occurs, then it may be a problem with using `GL_NEAREST` or with float rounding of texture coords and I can prepare a separate branch for testing that.
In either case, I'm trying to fix this blindly because I haven't been able to reproduce the issue on my hardware.

**Comment by RaptorParkowsky** [comment] 2016-03-22 11:11
Unfortunately after that fixes this pixelated fonts still occurs in the same locations.

Now I also found it also occurs here, in the ending splashscreen, if it would be helpful to know (it was also before yours totay fixes):
![schowek01](https://cloud.githubusercontent.com/assets/4019345/13949722/ed6d9430-f026-11e5-987a-4a7ce62a9b3a.png)

**Comment by krzys-h** [comment] 2016-03-24 15:24
I managed to reproduce it again by randomly switching resolutions. @piotrdz, could you see if you can reproduce it like that?
It's still a lot less visible than for @RaptorParkowsky though, mostly as single pixels near the edge of the characters (in this case it looks to be the space character?).
Now that I think about it, my one might be a completly different issue, as it appears for all characters of given type on screen.
![image](https://cloud.githubusercontent.com/assets/1517255/14021588/65557772-f1dc-11e5-8ca7-ca5ce190ae75.png)
![image](https://cloud.githubusercontent.com/assets/1517255/14021616/8696bb30-f1dc-11e5-935c-0a5debbd1fe2.png)

**Comment by krzys-h** [comment] 2016-03-24 17:28
I've managed to "fix" my issue, but it's not the cleanest fix ever...
```diff
-        Math::Point texCoord1(static_cast<float>(tex.charPos.x) / FONT_TEXTURE_SIZE.x,
-                              static_cast<float>(tex.charPos.y) / FONT_TEXTURE_SIZE.y);
-        Math::Point texCoord2(static_cast<float>(tex.charPos.x + tex.tileSize.x) / FONT_TEXTURE_SIZE.x,
-                              static_cast<float>(tex.charPos.y + tex.tileSize.y) / FONT_TEXTURE_SIZE.y);
+        float dx = 0.5f/FONT_TEXTURE_SIZE.x;
+        float dy = 0.5f/FONT_TEXTURE_SIZE.y;
+        Math::Point texCoord1(static_cast<float>(tex.charPos.x) / FONT_TEXTURE_SIZE.x + dx,
+                              static_cast<float>(tex.charPos.y) / FONT_TEXTURE_SIZE.y + dy);
+        Math::Point texCoord2(static_cast<float>(tex.charPos.x + tex.tileSize.x) / FONT_TEXTURE_SIZE.x - dx,
+                              static_cast<float>(tex.charPos.y + tex.tileSize.y) / FONT_TEXTURE_SIZE.y - dy);
```

**Comment by piotrdz** [comment] 2016-03-25 03:31
@krzys-h: well, with your fix I get pixelated text everywhere.
Instead, I think that my commit 4e331f1 will solve this as a kind of workaround. Now, only characters will be rendered, not characters and their surrounding tiles. There should be no overlap, unless the width of character falls exactly on power of 2 boundary, which is unlikely.

**Comment by RaptorParkowsky** [comment] 2016-03-25 13:43
Well, that's true. After that fix it get even more pixelated bugs:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/14045140/cd670162-f297-11e5-86b4-e55339b253e1.png)
![schowek02](https://cloud.githubusercontent.com/assets/4019345/14045143/d43ddad8-f297-11e5-8172-8c951ba318cd.png)
![schowek03](https://cloud.githubusercontent.com/assets/4019345/14045150/d9ded186-f297-11e5-831e-11e1ac54735b.png)
![schowek04](https://cloud.githubusercontent.com/assets/4019345/14045155/de0d9e7c-f297-11e5-8519-8c84ebae59b2.png)

**Comment by krzys-h** [comment] 2016-03-25 13:47
My fix didn't even get applied in the repo (and it does not cause pixelated text for me). @piotrdz's fix made no noticeable difference at all for me

**Comment by DavivaD** [comment] 2016-03-28 16:42
I can confirm this bug (graphics engine: gl14)
![confirmed](https://cloud.githubusercontent.com/assets/15150065/14083241/d771827a-f514-11e5-88a6-05d35a073e0e.png)

**Comment by tomangelo2** [comment] 2016-03-28 17:01
@DavivaD: which OS do you have?

**Comment by DavivaD** [comment] 2016-03-28 17:09
Windows 7 Home Premium x64

**Comment by MrSimbax** [comment] 2016-03-31 16:14
Not sure if this is related, but guess what, odd font rendering happened for me too.
![](http://i.imgur.com/i1zQNxg.png)

**Comment by piotrdz** [comment] 2016-04-03 09:42
I've finally reproduced this issue by using software renderer. It should be fixed by 72f966b.

**Comment by MrSimbax** [comment] 2016-04-03 10:28
It's better, but there are still little bugs.
![](http://i.imgur.com/nN9uWAo.png)

**Comment by krzys-h** [comment] 2016-04-03 19:36
I can't reproduce this issue anymore, although in my case there was never any text deforming, only characters from neighboring tiles being visible.

**Comment by piotrdz** [comment] 2016-04-06 09:10
As I suspected, the root cause of the remaining rendering artifacts is floating-point rounding. I have a very ugly fix for this which I will commit once I clean it up a little bit.
However, to clean this up properly and avoid similar problems in the future means rewriting UI positioning and size calculations everywhere. I wonder if this is worth the effort if we are to move to CEGUI anyway.

**Comment by krzys-h** [comment] 2016-04-07 15:12
After 71a77c77f6d94c84b0aaf02772ea7d7d104b6cf9, the text looks a lot different than it used to. Additionally, underlines on links in SatCom are invisible.

Before:
![image](https://cloud.githubusercontent.com/assets/1517255/14356056/98bb249c-fce3-11e5-852c-3c346e37b0e0.png)

After:
![image](https://cloud.githubusercontent.com/assets/1517255/14355957/2c62532e-fce3-11e5-8da9-9fdc49181a33.png)

**Comment by piotrdz** [comment] 2016-04-08 09:35
@krzys-h: I've fixed the display of highlights.

It's not surprising that the text looks different because now it is actually aligned to pixel boundaries, as it should be. Previously, it was almost always rendered at some uneven pixel position and blended onto the surrounding pixels which made it look a bit thicker than it would normally be.

**Comment by MrSimbax** [comment] 2016-04-08 09:47
This issue no longer occur for me.

**Comment by krzys-h** [comment] 2016-04-08 16:30
Yup, everything seems to be fine now.

**Closed by krzys-h** 2016-04-08 16:30 UTC
Labels: bug, graphics, latest dev only, ui
