### ISSUE TITLE
Colobot crash on loading saved mission

### ISSUE THREAD

**Issue by lisa50469** [colobot/colobot#832] opened 2016-09-11 19:56 UTC
Linux Ubuntu all updates, running from the PPA
# Unhandled exception occurred!
# SIGSEGV, segmentation fault

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
# including information on what you were doing before this happened and all the information below.

You seem to be running a custom compilation of version 0.1.8-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
# Last started level was: category=custom chap=1 rank=5

Sorry for inconvenience!

lisa@lisa-Inspiron-7720:~$ colobot
[INFO](Done.): Colobot: Gold Edition 0.1.8-alpha starting
[INFO](Done.): Creating CApplication
[WARN]: Unable to load mods from directory '/usr/share/games/colobot/mods': boost::filesystem::directory_iterator::construct: No such file or directory: "/usr/share/games/colobot/mods"
[INFO](Done.): Loading mod: '/home/lisa/.local/share/colobot/mods/True Levels 2.zip'
[INFO](Done.): Data path: /usr/share/games/colobot
[INFO](Done.): Save path: /home/lisa/.local/share/colobot
[INFO](Done.): Opening audio device...

[INFO](Done.): CApplication created successfully
[INFO](Done.): Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO](Done.): Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO](Done.): Error on parsing config file: No such node (Experimental.MSAA)
[INFO](Done.): Error on parsing config file: No such node (Experimental.VSync)
[INFO](Done.): No joysticks detected
[INFO](Done.): Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO](Done.): Creating CDevice - OpenGL 1.4
[INFO](Done.): OpenGL 3.0 Mesa 11.2.0
[INFO](Done.): Mesa DRI Intel(R) Ivybridge Mobile 
[INFO](Done.): Shadow mapping available (core)
[INFO](Done.): Anisotropic filtering available
[INFO](Done.): Maximum anisotropy: 16
[INFO](Done.): Multisampling supported, max samples: 8
[INFO](Done.): Auto-detecting VBO support
[INFO](Done.): Core VBO supported
[INFO](Done.): Maximum texture units: 8
[INFO](Done.): Maximum texture size: 8192
[INFO](Done.): Framebuffer supported (ARB)
[INFO](Done.): Maximum renderbuffer size: 8192
[INFO](Done.): CDevice created successfully
[INFO](Done.): Closing joystick
[INFO](Done.): Created shadow map texture: 1024x1024, depth 32
[INFO](Done.): Reseting world on phase change...
[INFO](Done.): Simulation speed = 1.00
[INFO](Done.): Loading level: levels/custom/Amber/level005/scene.txt
[WARN]: This level is using deprecated way of defining win scene. Please remove the win= parameter in EndingFile.
[WARN]: This level is using deprecated way of defining lost scene. Please change the lost= parameter in EndingFile from 0 to "levels/other/lost000.txt".
[ERROR]: Error opening file with PHYSFS: "textures/shadow00.png"
[ERROR]: Couldn't load texture 'textures/shadow00.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow01.png"
[ERROR]: Couldn't load texture 'textures/shadow01.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow02.png"
[ERROR]: Couldn't load texture 'textures/shadow02.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow03.png"
[ERROR]: Couldn't load texture 'textures/shadow03.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow04.png"
[ERROR]: Couldn't load texture 'textures/shadow04.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow05.png"
[ERROR]: Couldn't load texture 'textures/shadow05.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow06.png"
[ERROR]: Couldn't load texture 'textures/shadow06.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow07.png"
[ERROR]: Couldn't load texture 'textures/shadow07.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow08.png"
[ERROR]: Couldn't load texture 'textures/shadow08.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow09.png"
[ERROR]: Couldn't load texture 'textures/shadow09.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow10.png"
[ERROR]: Couldn't load texture 'textures/shadow10.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow11.png"
[ERROR]: Couldn't load texture 'textures/shadow11.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow12.png"
[ERROR]: Couldn't load texture 'textures/shadow12.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow13.png"
[ERROR]: Couldn't load texture 'textures/shadow13.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow14.png"
[ERROR]: Couldn't load texture 'textures/shadow14.png': Unable to open file, blacklisting
[ERROR]: Error opening file with PHYSFS: "textures/shadow15.png"
[ERROR]: Couldn't load texture 'textures/shadow15.png': Unable to open file, blacklisting
# Unhandled exception occurred!
# SIGSEGV, segmentation fault

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
# including information on what you were doing before this happened and all the information below.

You seem to be running a custom compilation of version 0.1.8-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=7)
# Last started level was: category=custom chap=1 rank=5

Sorry for inconvenience!
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
AL lib: (EE) alc_cleanup: 1 device not closed
lisa@lisa-Inspiron-7720:~$

**Comment by tomangelo2** [comment] 2016-09-11 21:14
Does it happen only for custom maps, or build-in maps cause crash too?
Can you run game with gdb and attach its logs there?

**Comment by lisa50469** [comment] 2016-09-12 02:45
I removed the custom maps.  I'll watch and report if it continues.

**Comment by lisa50469** [comment] 2016-09-12 03:59
No more crashes.  I've been playing without any add-ons.  Saving and loading just fine.  I do wish there was a sandbox to play with in the original without having to get a add-on.

**Comment by True-Destroyer** [comment] 2016-09-29 11:07
Modpack author here, the problem seems to be with some shadow textures.
[ERROR]: Error opening file with PHYSFS: "textures/shadow0x.png"
[ERROR]: Couldn't load texture 'textures/shadow0x.png': Unable to open file, blacklisting
These are not part of my mods.
It may be memory issues on your computer, caused indirectly by my levels - my levels spawn lots of stuff, textures are high res, and algorithms perform lots of iterations per second - you may want to try lowering your graphic settings - that's what I deducted from the log you posted. Lower maximum anisotropy, and consider lowering shadow resolution or disabling dynamic shadows.

**Comment by krzys-h** [comment] 2016-11-11 12:40
I'm assuming this is duplicate of #765. If it happens again in the latest dev branch, please reopen this issue.

**Closed by krzys-h** 2016-11-11 12:40 UTC
Labels: crash
