### ISSUE TITLE
Clicking the 'categories' link in Windows build may cause crash

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#619] opened 2015-08-30 07:43 UTC
I got this with recent CI builds e.g. build 97:
http://compiled.colobot.info/jenkins/view/colobot-gold-download/job/colobot-gold/branch/dev/97/

Steps to reproduce:
- Stop (if running) and start colobot (to start from a well-defined state)
- Start e.g. the first Earth mission
- Press F2 to display the CBOT programming help
- Click on the 'categories' link (under 'Constants')
- Colobot crashes:
```
[DEBUG]: Starting music...
[DEBUG]: Music loaded from cache
[INFO]: Game paused - SatCom opening animation
[INFO]: Game resumed
[INFO]: Game paused - SatCom

Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot
/colobot/issues
including information on what you were doing before this happened and all the in
formation below.
==============================
You are running version git-HEAD~r6711154 from CI build #97

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=1 rank=1
==============================

Sorry for inconvenience!
```
In this help page if you select first e.g. the 'extern' link, then click the 'back' button, and only then click 'categories', then it does not crash.
In Linux I could not reproduce this.

**Comment by piotrdz** [comment] 2015-08-30 20:14
Seems to be fixed now.

**Comment by attila123** [comment] 2015-08-30 22:21
Unfortunately it still crashes with the latest Jenkins build 99:

```
[DEBUG]: Music loaded from cache
[INFO]: Game paused - SatCom opening animation
[INFO]: Game resumed
[INFO]: Game paused - SatCom

Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot
/colobot/issues
including information on what you were doing before this happened and all the in
formation below.
==============================
You are running version git-HEAD~ra47da3f from CI build #99

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=1 rank=1
==============================

Sorry for inconvenience!
```

**Comment by krzys-h** [comment] 2015-09-01 14:40
Unfortunately, I still can't reproduce this :( Tried the exact same build on Windows and no crash. Could you try to at least provide a gdb backtrace?

**Comment by attila123** [comment] 2015-09-01 22:37
Hi,
Now I noticed that it does not crash in full screen (or if the game was started in full screen).
So you need to make sure to start up the game in windowed mode.
In my laptop it also does not crash in 1600 x 900 resolutions, but does crash in all the others: 1024 x 768, 800 x 600, 640 x 480.
Also, it does not crash if I try to run it in gdb (tried cygwin and mingw ones).
So it seems to be some nasty bug.
So what I can recommend is to configure the game to windowed mode and target resolution and restart it and try to reproduce.
Probably sysinternals procdump utility could be used to create the dump at crash.
E.g. <path to>\procdump.exe -s 10 -n 10 -ma -x colobot.dmp colobot.exe
-> will create procdumps periodically, I used this method a few years ago to debug something.

**Comment by attila123** [comment] 2015-09-01 23:04
I also tried on another machine, which is Win 7 SP1 32 bit, and totally different HW.
It also crashed in certain resolutions sometimes even in full screen, sometimes it didn't.
The strange thing is that when it crashed it did not display the dialog as usual, but the application just exited and the log window also disappeared.

**Comment by attila123** [comment] 2015-09-01 23:18
Also, if I run the colobot.exe in compatibility mode for e.g. Win XP SP3, it does not reproduce in either computer. When I unselect the comp. mode, it crashes again.

**Comment by attila123** [comment] 2015-09-01 23:36
It would be also nice if colobot itself could print the strack trace on crash.
In Windows there is a library called StackWalker for this.
This also seems to be some detailed article (did not read it):
http://oroboro.com/stack-trace-on-crash/

**Comment by krzys-h** [comment] 2015-09-10 19:53
I still can't reproduce it. Since there exists a workaround, I'll move this to 0.1.7 milestone for now

**Comment by RaptorParkowsky** [comment] 2015-09-11 12:35
For me it crashes every time in every resolution. Even in fullscreen mode.

**Comment by krzys-h** [comment] 2015-09-14 18:52
Sometimes I hate the auto-close feature

**Comment by attila123** [comment] 2015-09-28 20:12
I just tested it with latest dev build # 152. It still crashes, in my laptop when the game is started in Windowed mode, and resolutions lower than 1600. In 1024 it crashes even when I press F2 (after the animation), in 800 and 640 I also have to click the 'categories' link. So it looks like SDL2 did not do any magic here. :(

**Closed** 2016-02-11 17:49 UTC
Labels: bug, SatCom, ui
