### ISSUE TITLE
Pathfinding fails too often

### ISSUE THREAD

**Issue by Kreyren** [colobot/colobot#1397] opened 2021-02-28 18:42 UTC
Pathfinding fails too often in the game and it seems to be impossible to make a code adjustments to handle it.

### Steps to reproduce
1. Open `On the offense` 
2. Go in flybot and execute the following command:
```CBOT
// This program makes the bot to look for batteries and deliver them on specified location
public extern bool object::scavangeBattery(string location) {
	object item;
	point start;
	
	// If not holding a battery
	if(this.load == null) {
		goto(radar(PowerCell).position);
		grab();
	} else {
		goto(radar(SpaceShip).position);
		drop();
	}
	
	return true;
}
```
3. Run the command and expect flybot to complain about `goto: Inaccesible location` requiring either to re-execute the `goto` command or turn the bot 90 degrees left and re-execute the command.
5. Wait for the bot to get stuck while trying to get the battery.

![image](https://user-images.githubusercontent.com/11302521/109429514-59c90d80-79fc-11eb-8512-16373c428395.png)

### Proposed solution
1. Make the goto to not fail instantly assuming that in most cases the re-execution of `goto` command fixes the issue
2. Make the bot to try to turn as that seems to fix the issue
3. In situation such as picture above where bot is unable to get the battery, because of another bot blocking the landing area make it to either fly up move to a random direction and retry or make it possible for the pathfinding to avoid insufficient landing spots.
4. Define "Nexus" meaning place next to the spaceShip that the bots will return to in case they can't reach some area.

**Comment by MrSimbax** [comment] 2021-03-01 16:10
Duplicate of #336

**Closed by MrSimbax** 2021-03-01 16:10 UTC
Labels: CBOT, bug, duplicate
