### ISSUE TITLE
Cannot build from source nor build from AUR

### ISSUE THREAD

**Issue by orendanniel015** [colobot/colobot#1195] opened 2018-08-11 21:22 UTC
Hello everyone!
I am trying to install the game on my computer. so I tried installing from the AUR and it failed it gave me an error message similar to the same one here https://github.com/colobot/colobot/issues/1180.
After that I have tried to install from source which also failed(both stable branch and dev branch), I even ran cmake with ignore errors flag which did let it compile but the game couldn't launch.

```
/tmp/pamac-build-oren/colobot-gold/src/colobot-colobot-gold-0.1.11.1-alpha/src/graphics/model/model_output.cpp: In function ‘void Gfx::ModelOutput::WriteOldModel(const Gfx::CModel&, std::ostream&)’:
/tmp/pamac-build-oren/colobot-gold/src/colobot-colobot-gold-0.1.11.1-alpha/src/graphics/model/model_output.cpp:331:16: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 20 equals destination size [-Werror=stringop-truncation]
         strncpy(t.texName, triangle.tex1Name.c_str(), 20);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/colobotbase.dir/build.make:752: src/CMakeFiles/colobotbase.dir/graphics/model/model_output.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:187: src/CMakeFiles/colobotbase.dir/all] Error 2
```
I also tried to change this part to `strncpy(t.texName, triangle.tex1Name.c_str(), 20);` writing 19 instead of 20 but then I ran to another error message.

I have cmake 3.11.4-2
gcc 8.2.0-2

when compiling the game with errors:
```
Error in CEngine::Init()

Please see the console output or log file
to get more information on the source of error


```
what should I do ?
thanks for the help

**Comment by krzys-h** [comment] 2018-08-12 05:48
We are aware of the warning issues on gcc8 and will try to fix them soon.

The error you got after compiling with warnings disabled seems unrelated, could you show the complete game log? Are you sure you have downloaded and installed the data submodule?

**Comment by CHmSID** [comment] 2018-08-12 15:16
I'll have a look at it once I install Arch with GCC 8.2. I can't reproduce this error on my system with GCC 8.1

**Comment by orendanniel015** [comment] 2018-08-13 17:14
thanks for the quick response!
if these are warning is there a way to tell the AUR to ignore warnings?

**Comment by CHmSID** [comment] 2018-08-13 17:58
Probably in the makepkg file but I've never done it before. When your AUR helper asks if you want to look at pkgbuild or something similar then say yes and see if you can edit that. Then remove the relevant compile flag, i think it'll be -Werror

**Comment by krzys-h** [comment] 2018-08-15 19:19
@orendanniel015 are you sure about the versions? GCC 8.2.0-1ubuntu2, cmake 3.11.2, unable to reproduce

**Comment by CHmSID** [comment] 2018-08-18 07:33
I can confirm the error is happening on Arch with GCC 8.2.0 and cmake 3.11.4. I'll try to get it fixed.

**Comment by mikijov** [comment] 2018-12-09 21:51
I am still getting this error. I was able to make it build by editing PKGBUILD when installing.
`$ yay -S --nodiffmenu --editmenu colobot-gold`
then on the 'cmake' like add this at the end
`-DCMAKE_CXX_FLAGS_INIT="-Wno-error -Wno-stringop-truncation -Wno-error=format-overflow"`

**Comment by Erihel** [comment] 2018-12-09 22:37
This issue was addressed in dev branch. Aur package is for latest release so it does not have this fix. I've emailed @krzys-h suggesting to make a bugfix release some time ago.

In the meantime I've updated aur package with workaround and it should compile (tested on GCC 8.2.1).

**Closed** 2018-12-18 20:41 UTC
Labels: compilation
