### ISSUE TITLE
Mission 3-3 No energy in subsoil

### ISSUE THREAD

**Issue by mglee72** [colobot/colobot#692] opened 2015-12-11 22:51 UTC
No energy in subsoil even on blue flag area.

**Comment by tomangelo2** [comment] 2015-12-11 23:33
Just have checked latest dev and there is no such problem. Did you had this on Release version?

**Comment by mglee72** [comment] 2015-12-11 23:35
Yeah it was on alpha 0.1.6, master branch.

**Comment by tomangelo2** [comment] 2015-12-11 23:51
That's strange, I've just tested Release build and it works. Maybe official release contain some hidden bug?

**Comment by mglee72** [comment] 2015-12-11 23:52
Sorry, forgot to note that the build was done on Mac OSX el capitan, following the install-macosx readme.

**Comment by kurg** [comment] 2015-12-23 14:13
I just tested it on my PC : Windows 10, Colobot 0.1.6 and it works fine.
![mission3 3enegy](https://cloud.githubusercontent.com/assets/7715144/11977930/f4d4fefa-a965-11e5-81ce-5463ca0d1b57.png)

**Comment by krzys-h** [comment] 2016-04-03 19:52
@piotrdz could you test this on OS X build?

**Comment by krzys-h** [comment] 2017-06-03 20:28
Unable to reproduce, closing

**Closed by krzys-h** 2017-06-03 20:28 UTC
Labels: Needs verification
