### ISSUE TITLE
Cannot programmaticaly 'factory' robots in BotFactory

### ISSUE THREAD

**Issue by Otaka** [colobot/colobot#421] opened 2015-01-05 12:20 UTC
In "Mission on the Moon" there is already prebuilt BotFactory on the ground. If I try to create another robot with WheeledGrabber with program botFactory.factory(WheeledGrabber,"some program"), exception appears: "nullptr, please tell to the developers". 

If I build BotFactory by myself, method "factory" works well,but if I save and then load level, BotFactory becomes broken again.

Colobot 0.1.4-alpha

**Comment by krzys-h** [comment] 2015-01-08 17:59
Could you make sure this still happens in latest version? I can't reproduce this, but I didn't try before 61b186343f506a5c702c0004636e0e90c1a60a47 so I'm not sure if it's fixed or not.

**Comment by krzys-h** [comment] 2015-03-19 18:06
I can't reproduce this, so I'm assuming it was already fixed in 61b186343f506a5c702c0004636e0e90c1a60a47.

**Closed by krzys-h** 2015-03-19 18:06 UTC
Labels: bug, CBOT, Needs verification
