### ISSUE TITLE
Alt + tab-ing out of the game should pause the game...

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#609] opened 2015-08-28 22:37 UTC
... at least if the game was in full screen.
I guess windowed mode is mainly only used for level development. Why else would anyone play in windowed mode??? Maybe in case of some serious HW limitations, but I think we can ignore the windowed mode for this issue, right?
If I alt + tab out of the game and it continues, bad things may happen. E.g. if my winged bot was over water, it may eventually drop to the water and be destroyed, ants / wasps may destroy the base, etc.
Instead it should bring up the menu, which is activated by pressing the Esc key.

**Comment by krzys-h** [comment] 2015-08-29 08:38
:+1:

**Comment by attila123** [comment] 2015-08-29 08:58
Thx. alpha-0.1.5 milestone? Not 0.1.6?
BTW, should 0.1.6 be beta at least?

**Comment by RaptorParkowsky** [comment] 2015-08-29 11:24
People who plays with Steam community overlay would also pause the game after Shift + Tab hotkey.

**Comment by krzys-h** [comment] 2015-08-29 13:35
We can't detect the Steam overlay I believe without access to the official APIs

**Comment by RaptorParkowsky** [comment] 2015-08-29 13:42
But hotkey alone could be detected even if the game isn't running under Steam overlay I think. I guess @Emxx52 can bring more info about how is that feature working with other non-Valve games.

**Comment by krzys-h** [comment] 2015-08-29 14:05
Catching the key combination may be impossible if Steam catches it first, but I'm not sure

**Comment by attila123** [comment] 2015-08-29 14:30
Hmm, I did not mean to detect the exact key combination, it may be problematic in other ways, too (e.g. someone might remap to some other key combination e.g. under Linux).
Could the application itself detect that it's no longer running in the foreground?
I guess it can be platform dependent.

**Comment by krzys-h** [comment] 2015-08-29 14:32
We can detect when the window is deactivated, see https://github.com/colobot/colobot/blob/master/src/app/app.cpp#L1149-L1161. It's not used anywhere at the moment.
I'm not sure if this works for steam overlay though.

**Comment by RaptorParkowsky** [comment] 2015-08-29 14:59
So we can use that feature. About Steam overlay, well, that was only my suggestion. We can add another issue for that in more adequate time.

**Comment by Emxx52** [comment] 2015-08-30 13:18
@RaptorParkowsky Detecting a key combination is not the best idea... Completely useless when the user decides to remap the combination, it could also be the cause of situations where the overlay is active but the game is not paused. We will implement a proper listening for **Steamworks**' callbacks in the future - particularly for the following subject the *Overlay*'s activation/deactivation callback.

**Comment by krzys-h** [comment] 2015-08-31 10:02
I can't get this to work - at least on Linux, SDL reports only mouse going in/out of the window and the window deactivation is not reported :/ (we are always getting only SDL_APPMOUSEFOCUS in m_private->currentEvent.active.type)
I'm moving this issue to 0.1.7 and SDL2, unless @piotrdz knows what's wrong

**Closed** 2016-02-13 20:35 UTC
Labels: enhancement
