### ISSUE TITLE
Problem with if statement?

### ISSUE THREAD

**Issue by MariuszPL55** [colobot/colobot#638] opened 2015-09-17 10:03 UTC
This is the code:
![cbot if statement](https://cloud.githubusercontent.com/assets/7559579/9930426/e6c93f2a-5d33-11e5-8f6f-e776769c20f7.png)

and game will crash when code run into this step: if(o == null) (I know, because I checked that with wait commands) but.. This is the normal activity to check the exists of object and it is usually work, so I don't understand that.. In fact we can pull this object function, because if this code is in rest of method in object then all is right and works fine, but when I put it to this function then this crashes whole game.

**Comment by MrSimbax** [comment] 2015-09-17 12:12
It doesn't crash for me. Maybe the crash is connected with `instance.Build(cat);`? Could you show your class and call of the function `searchFor`?

This is the code I was testing and worked just fine for me (on map without `WingedShooter`).

```
public class Bot
{
	void Build(int cat)
	{
		message("Building");
		return;
	}
}

object searchFor(Bot instance, int cat)
{
	object o = search(cat);

	if (o == null)
	{
		instance.Build(cat);
		o = search(cat);
		return o;
	}
}

extern void object::Test()
{

	Bot instance();
	searchFor(instance, WingedShooter);

}
```

**Comment by MrSimbax** [comment] 2015-09-17 12:16
Also you should `return` something outside of the `if`, because function might end without returning anything if `o != null`. I'd call that undefined behaviour, but I'm not sure how this is handled in CBOT.

**Comment by MariuszPL55** [comment] 2015-09-17 12:37
```
public class Bot
{
	private object Robot;
	
	void Bot(object Robot)
	{
		this.Robot = Robot;
	}
	
	int Fuel()
	{
		return Robot.energyCell.energyLevel;
	}
	
	void Recharge()
	{
		float energyLevel;
		
		if( search(PowerStation) == null ) return;
		
		if( Robot.load.category != PowerCell )
		    energyLevel = 1;
		else
		    energyLevel = Robot.load.energyLevel;
		if( Fuel() < 0.2 || energyLevel < 1 )
		{
			object p = search(PowerStation);
			goto(p.position);
			
			while(true)
			{
				if( Fuel() == 1 )
				{
					if( Robot.load != null)
					    if( Robot.load.energyLevel == 1 )
					        break;
				}
			}
		}
	}
	
	void Build(int cat)
	{
		GetTitanium();
		Recharge();
		
		while(true)
		{
			goto(flatspace(Robot.position, 10, 10, 40, 8));
			drop();
			
			if( canbuild(cat) )
			{
				build(cat);
				break;
			}
		}
	}
	
	void BuildBot(int cat, string program)
	{
		message("Get titanium..");
		GetTitanium();
		message("Recharge..");
		Recharge();
		
		message("Search factory..");
		object bFactory = search(BotFactory);
		
		if(bFactory == null)
		{
			message("Build factory..");
			Build(BotFactory);
			bFactory = search(BotFactory);
		}
		
		message("Go to factory..");
		goto(bFactory.position);
		drop();
		move(-3);
		bFactory.factory(cat, program);
		
		GetPower();
		goto(bFactory.position);
		while( bFactory.busy() ) wait(0.05);
		
		while( !detect(cat) ) wait(0.5);
		
		drop();
		move(-5);
	}
	
	void Research(int cat)
	{
		GetPower();
		Recharge();
		
		object r = search(ResearchCenter);
		
		if(r == null)
		{
			Build(ResearchCenter);
			r = search(ResearchCenter);
		}
		
		goto(r.position);
		
		while( r.busy() )
		    wait(0.05);
		if( r.energyCell == null )
		    drop();
		else
		{
			drop(Behind);
			grab();
			turn(90);
			drop();
			turn(-90);
			grab(Behind);
			drop();
		}
		
		r.research(cat);
	}
	
	int GetLoad()
	{
		if( Robot.load != null )
		{
			return Robot.load.category;
		}
		else
		{
			return -1;
		}
	}
	
	void GetTitanium()
	{
		int load = GetLoad();
		if( load != -1 )
		{
			if( load != Titanium )
			{
				goto(space());
				drop();
			}
			else
			{
				return;
			}
		}
		
		object t = radar(Titanium, 0, 360, 0, 50);
		
		if(t != null)
		{
			message("My position: " + Robot.position, DisplayInfo);
			message("Target position: " + t.position, DisplayInfo);
			get(t);
		}
		else
		{
			makeTitanium();
		}
	}
	
	void GetPower()
	{
		int load = GetLoad();
		if( load != -1 )
		{
			if( load != PowerCell )
			{
				goto(space());
				drop();
			}
			else
			{
				Recharge();
				return;
			}
		}
		
		object r = search(ResearchCenter);
		
		if(r == null)
		{
			Build(ResearchCenter);
			r = search(ResearchCenter);
		}
		
		if(r.energyCell != null)
		{
			goto(r.position);
			
			while(r.busy()) wait(0.05);
			
			grab();
			Recharge();
			return;
		}
		
		object p = radar(PowerCell, 0, 360, 0, 50);
		
		if( p != null )
		{
			get(p);
			Recharge();
		}
		else
		{
			makePower();
		}
	}
	
	void makeTitanium()
	{
		object tOre = radar(TitaniumOre, 0, 360, 0, 50);
		
		if(tOre != null)
		{
			get(tOre);
		}
		else
		{
			object d = search(Derrick);
			goto(d.position);
			waitFor(TitaniumOre);
			grab();
		}
		
		object c = search(Converter);
		
		if(c == null)
		{
			Build(Converter);
			c = search(Converter);
		}
		
		goto(c.position);
		drop();
		move(-2);
		
		wait(2);
		while(radar(Titanium, 0, 20, 0, 5) == null)
		{
			wait(0.05);
			
			if(radar(Converter, 0, 20, 0, 5) == null)
			{
				Build(Converter);
				return;
			}
		}
		
		move(2);
		if(grab() != 0)
		    makeTitanium();
	}
	
	void makePower()
	{
		GetTitanium();
		
		object p = search(PowerPlant);
		
		if(p == null)
		    Build(PowerPlant);
		
		goto(p.position);
		drop();
		
		wait(2);
		while(p.busy()) wait(0.05);
		
		grab();
	}
	
	void get(object item)
	{
		goto(item.position);
		grab();
	}
	
	void safeTitanium()
	{
		makeTitanium();
		goto(space());
		drop();
	}
}

void waitFor(int cat)
{
	while(true)
	{
		wait(0.5);
		bool result = detect(cat);
		
		if( result ) break;
	}
}

void waitFor(int cat, int time)
{
	wait(time);
	waitFor(cat);
}

extern void object::MyClasses()
{
	
}
```

This is whole code for Bot, when I removed that function and put it again and again and again in code then it works fine..

**Comment by krzys-h** [comment] 2015-09-25 21:39
Since this crash can't be reproduced, I'm closing this issue. Please let us know if it happens again.

**Closed by krzys-h** 2015-09-25 21:39 UTC
Labels: bug, CBOT, Needs verification
