### ISSUE TITLE
A mistake and colobot can't longer be started

### ISSUE THREAD

**Issue by HybridDog** [colobot/colobot#840] opened 2016-10-06 08:30 UTC
On linux, a whitespace can be set as player name when selecting the player, but when (re)starting colobot it crashes:

> colobot: […]colobot/src/level/robotmain.cpp:4850: void CRobotMain::SelectPlayer(std::__cxx11::string): Assertion `!playerName.empty()' failed.

Further information:

> SIGABRT, abort
> You seem to be running a custom compilation of version git-dev~r6b6eca6, but please verify that.
> The game was in phase PHASE_PLAYER_SELECT (ID=3)
> Last started level was: category=exercises chap=0 rank=0

How to reproduce:
- start colobot
- when the player selection menu appears, write a whitespace into the playername text field
- press esc to play with empty playername
- quit colobot and try to start again

To fix reset the player name, just edit colobot.ini.

**Comment by krzys-h** [comment] 2016-10-06 09:06
This can be easily fixed by removing the colobot.ini file (usually in C:\Users\username\colobot or ~/.local/share/colobot depending on your OS)

**Comment by RaptorParkowsky** [comment] 2016-10-06 11:00
I can't reproduce that with recent Windows build.
Username with only the whitespace character is playable, but the game can't create directory called " " and save the process into such directory. After restart game boot normally, but without access to user called " ", because there's no such directory. Usernames with whitespaces like "Raptor Parkowsky" can be created without any problem (at least on the Windows, I can't test it under the Linux now). Looks like it highly depend of the OS and their filename rules. For example you can't create filename with such characters like \ / < > * | " ? under the Windows which is obvious.

**Comment by tomaszkax86** [comment] 2016-10-06 12:31
Colobot should trim player name from whitespace characters at both ends and then check if it's empty. If it is empty, it should refuse to accept it and let player set another name. This way we'll avoid many problems.

**Comment by HybridDog** [comment] 2016-10-06 19:10
tomaszkax86, the assertion fails when starting colobot. Maybe executing playerName.empty() when pressing escape is enough to fix the bug?

RaptorParkowsky, in linux you can even set the name of a file/folder/link/fifo to line break. If you push a folder named line break in a git repository to github, it's hidden and you can only find it by downloading the repository (example: https://github.com/HybridDog/riesenpilz). Note that you can see the file names by pressing on the find file button, but you can't open them, github tells 404.

**Closed** 2016-11-11 16:13 UTC
Labels: bug, crash
