### ISSUE TITLE
Robot programs list break after loading saved game.

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#797] opened 2016-07-01 13:23 UTC
When we load a savegame (both created when game crashed and normal saves), programs marked as read-only disappear. Also actually running programs cannot be aborted with Stop button.
![screenshot_3](https://cloud.githubusercontent.com/assets/4140449/16522662/804c1836-3f9f-11e6-9a51-5a9da576d4c0.png)

**Comment by Ceeee** [comment] 2016-10-29 11:31
This also happened to me -without- restoring after a crash. Simply loading the (normally stored) save game after a crash did this. (Win 0.1.8, different levels)

**Comment by RaptorParkowsky** [comment] 2016-11-01 09:45
I can confirm that only for newly built bots while playing the level. Bots that are in the level from very beginning with read-only programs and newly written programs works flawlessly.

**Comment by Ceeee** [comment] 2016-11-08 06:58
According to the closing comment for #851 the heading of this should be adapted to reflect normal save games affected, without a crash or restoring after one. That would prevent future duplicates ;-)

**Comment by rbcat** [comment] 2018-02-03 04:18
Unlike @RaptorParkowsky I can comfirm this issue for all the bots, including those that were since beginning of game. However, it appears only if these programs are editable, i.e. scriptReadOnlyX=false was specified in scene.txt.

**Closed** 2018-05-07 19:01 UTC
Labels: bug, ui
