### ISSUE TITLE
What about make sub Release 2.1.0 etc of master branch... In near time?

### ISSUE THREAD

**Issue by X64E** [colobot/colobot#1502] opened 2022-02-12 19:06 UTC
What do you think?

I think this list is enough to release a sub release:

UTF-8 input bug https://github.com/colobot/colobot/pull/1487 (It's not ready yet but it needs to be finished)
Satcom offset fix https://github.com/colobot/colobot/pull/1464
Enchance Portico unit https://github.com/colobot/colobot/pull/1460
Slotted object interface https://github.com/colobot/colobot/pull/1444
Translations etc..

**Comment by MrSimbax** [comment] 2022-02-12 19:52
Duplicate of https://github.com/colobot/colobot/discussions/1384.

**Closed by MrSimbax** 2022-02-12 19:52 UTC
