### ISSUE TITLE
SIGSEGV, segmentation fault

### ISSUE THREAD

**Issue by przemo420** [colobot/colobot#1190] opened 2018-07-30 15:55 UTC
Hi, when i compile this code:

```
public class baza {
	object pojazd, tytan;
	object ss = radar(SpaceShip);
	
	void construct(object p) {
		pojazd = p;
	}
	
	void wezKostke(object pojazd) {
		if(pojazd.load != null && pojazd.load.category != Titanium) {
			goto( space(
		}
	}
	
	void buduj(int budynek, object pojazd) {
		do {
			if(pojazd.load == null) {
				wezKostke();
			} else if(pojazd.load.category != Titanium) {
				drop();
				wezKostke();
			}
			
			goto( flatspace(ss.position, 5) );
		} while(canbuild(budynek) == false);
	}
}
extern void object::rozpocznijBudowe()
{
	baza construct( this );
	
	object tytan = radar(Titanium);
	object pojazd = this;
	
	bool mContinue = false;
	
	if(tytan == null) {
		message("Nie znaleziono kostki tytanu.", DisplayError);
		return;
	}
	
	goto(tytan.position);
	grab();
	
	goto(  );
	
	do {
		if(canbuild())
		
		grab();
	} while(mContinue);
```

The game was crashed.

![image](https://user-images.githubusercontent.com/2150486/43408448-b0581646-9421-11e8-8471-3bc0d984e1ea.png)

**Comment by krzys-h** [comment] 2018-08-05 20:43
In original Colobot it was incorrect to initialize class member like that, unless @melex750 changed something about that this should have been a compile error. You have to use the constructor if you want to initialize a class member with a result of a function call.

Oh, and by the way, the function `void construct(object p)` should be defined as `void baza(object p)` if you want it to be the constructor which it looks like you do.

**Comment by melex750** [comment] 2018-08-06 13:41
Related issue #981
That bug also exists in 0.1.6 and, as far as I can tell, since "Initial commit".

The initial expression for a class member is **[compiled with this code](https://github.com/colobot/colobot/blob/dev/src/CBot/CBotClass.cpp#L740)**.
Currently there is no way to block compiling a function call in that case.

One possible fix is to add an option to CBotCStack that blocks compiling
any function call at the current and subsequent stack frames.

Math functions, like pow(), rand(), sqrt(), work for initializing class members,
maybe some function calls can be allowed and others blocked.

**Comment by hexagonrecursion** [comment] 2024-05-12 08:42
This issue appears to be a duplicate of #981

**Closed** 2024-05-13 21:13 UTC
Labels: bug, CBOT, crash
