### ISSUE TITLE
SIGSEV Segmetation Fault (dev-modernize-build-system)

### ISSUE THREAD

**Issue by Python-Sargent** [colobot/colobot#1631] opened 2023-11-28 16:26 UTC
The game builds but running `./colobot -datadir ./data` gives a blank window with only the mouse particles.
After a few seconds of loading the music comes up and then another few seconds and the error popup comes up with this error:

```
Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version git-dev-modernize-build-system~r4f438f04, but please verify that.

The game was in phase PHASE_PLAYER_SELECT (ID=3)
Last started level was: category=exercises chap=0 rank=0
==============================

Sorry for inconvenience!
```

Should I be using the `dev` branch?

**Comment by hexagonrecursion** [comment] 2023-11-28 16:43
blank window? Like [missing shades](https://github.com/colobot/colobot/pull/1616#discussion_r1399593359)?

> Should I be using the dev branch?

If you want to develop and contribute a patch - probably yes. Master is unfortunately quire far behind dev - branches made from it might have issues merging into dev. Building master worked for me with no issues if I recall correctly (except having to figure out all the dependencies; [this helped](https://github.com/colobot/colobot/blob/84ac0d3ba8bc7c590da0b999f132f765f6d56ed1/.github/workflows/build.yml#L17))

**Comment by Python-Sargent** [comment] 2023-11-28 17:07
I tried building in the `dev` branch, but I couldn't even get it to open a window when I started it up.

```
[INFO]: Segmentation fault (core dumped)
```

**Comment by Python-Sargent** [comment] 2023-11-28 17:21
Building as provided in the INSTALL.md throws this error when running `make`

```
[ 17%] Linking CXX shared library libCBot.so
/usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): warning: relocation against `_ZTISt12out_of_range@@GLIBCXX_3.4' in read-only section `.text.unlikely'
/usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt16invalid_argument@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CBot/CMakeFiles/CBot.dir/build.make:1250: CBot/libCBot.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:686: CBot/CMakeFiles/CBot.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

running `make -fDIC` throws this error:

```
make: PIC: No such file or directory
make: *** No rule to make target 'PIC'.  Stop.
```

NOTE: I'm using sudo because I'm building with my prefix in a protected directory: `/usr/share/colobot`

**Comment by tomangelo2** [comment] 2023-11-29 13:48
A quick workaround would be to set up cmake with `-DCBOT_STATIC=1` flag.

#1632 turned out to have some other compilation issues, so it won't be merged just yet.

**Comment by hexagonrecursion** [comment] 2024-09-08 04:46
> Building as provided in the INSTALL.md throws this error when running `make`
> 
> ```
> [ 17%] Linking CXX shared library libCBot.so
> /usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): warning: relocation against `_ZTISt12out_of_range@@GLIBCXX_3.4' in read-only section `.text.unlikely'
> /usr/bin/ld: ../colobot-common/libColobot-Common.a(stringutils_generic.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt16invalid_argument@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [CBot/CMakeFiles/CBot.dir/build.make:1250: CBot/libCBot.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:686: CBot/CMakeFiles/CBot.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2
> ```
> 
> running `make -fDIC` throws this error:
> 
> ```
> make: PIC: No such file or directory
> make: *** No rule to make target 'PIC'.  Stop.
> ```
> 
> NOTE: I'm using sudo because I'm building with my prefix in a protected directory: `/usr/share/colobot`

* This part is a duplicate of #1617 - #1632

**Comment by hexagonrecursion** [comment] 2024-09-08 07:26
1. Unfortunately you did not post the exact commands you used to compile the game
2. Unfortunately you did not post log.txt

This makes troubleshooting this issue require a lot of guesswork.

> a blank window with only the mouse particles

-datadir probably does not contain the shaders

> the music comes up

-datadir does contain the music

You wrote that you used `./colobot -datadir ./data`. Are you sure it wasn't `../data`  (two dots)?

Looking at 4f438f04 - if `build/data` contains the music it must also have the shaders. This is why I suspect you used 
```
./colobot -datadir ../data
```

* `-datadir ../data` is unsupported. Instructions on how to correctly setup the development environment will be updated when  #1616 is merged

**Closed** 2024-10-20 12:06 UTC
Labels: compilation, crash, Not enough information
