### ISSUE TITLE
Crash "Unhandled exeception" at beginning of mission 4.1

### ISSUE THREAD

**Issue by Nartagnan** [colobot/colobot#1360] opened 2020-10-04 17:26 UTC
Hi!

Second time the game crash at the same position.

I play it windowed, on Kubuntu 18.04
Beginning of Mission 4.1, I have just the time to read the Statcom info (F1)

A 3rd try and it worked perfectly, I could finish the mission.

Here is the full error message

Unhandled exception occurred!
==============================
SIGFPE, arithmetic exception
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You are running official 0.1.11-alpha build.

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=4 rank=1

**Comment by tomangelo2** [comment] 2020-10-04 17:30
0.1.11 is outdated version, try this one instead https://colobot.info/files/releases/0.1.12-alpha/colobot-gold-0.1.12-alpha-linux-appimage-x86_64.zip

**Comment by nextghost** [comment] 2021-01-02 14:27
This is most likely a duplicate of #1128. It was fixed in 0.1.12.

**Closed** 2021-03-26 08:14 UTC
Labels: Needs verification, crash
