### ISSUE TITLE
Segmentation Fault  on Game Over

### ISSUE THREAD

**Issue by Willyanto39** [colobot/colobot#1188] opened 2018-07-25 11:41 UTC
I encountered a bug while playing this game.

Error Message:
You are running official 0.1.11-alpha build.
The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=freemissions chap=1 rank=1

What I did to trigger this error:
1. Use the astronaut to carry a titanium cube, titanium ore or battery cell.
2. Use Phazer Shooter (not tested on other bots) to kill the astronaut.

After testing this game for a few times, it looks like this bug can be triggered when the astronaut dies while carrying something.

**Comment by tomangelo2** [comment] 2018-07-25 21:15
In the meantime I found out that you don't really need to carry anything, also reproducible for other bots, but due to their low damage it's easier to just use Phazer.

**Comment by krzys-h** [comment] 2018-08-05 20:44
Pleeeaseee not a bug with destruction of related objects again :/

**Comment by iceslab** [comment] 2018-10-10 17:53
Issue is a duplicate of #1203, fixed by #1206

**Closed** 2019-02-07 12:44 UTC
Labels: bug, crash
