### ISSUE TITLE
Strange problems when resizing game window or changing resolution when we are doing mission

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#339] opened 2014-10-21 11:34 UTC
There is separate problem with Nvidia and AMD/ATI GPUs.
Radeon: models and textures disappear. When texture is refreshed (like power cells) they are visible again. When we create new bot (like produce(); for example) an old models/textures are overwritten by new. examples: http://prntscr.com/4y30l6  (TrackedOrgaShooter was created by produce();, that's when SpaceShip (yup, these flying objects is SpaceShip with disappeared and somehow overwritten textures) become visible) http://i.imgur.com/sbDhbgy.png  (this is Me, when flying) http://i.imgur.com/ItOrYEI.png (produced NuclearCell, then invisible nozzle of WingedGrabber started looking like NuclearCell), https://www.dropbox.com/s/dlkppw0fdk4u641/VIDEO0010.3gp (video, when i'm running around SpaceShip).
Nvidia: after resizing window a game just crash. Log from IRC discussion http://wklej.org/hash/8318d8c3e72/
Linux users doesn't have this problem, it looks like Windows only problem.

**Comment by krzys-h** [comment] 2015-06-05 16:51
Why was this even closed?

**Comment by CoLoRaptor** [comment] 2015-06-05 20:37
@krzys-h Because we disabled possibility to change screen resolution in Windows builds to not allow frequent crashes of the game in 0.1.4. Possibly we thought that in future we will open another issue to change that after graphic or texture reloading refactoring.

**Comment by krzys-h** [comment] 2015-06-06 21:55
Yeah, this issue was supposed to stay open for the issue with texture reloading

**Comment by krzys-h** [comment] 2015-06-26 17:21
Actually, this is now a duplicate of #449

**Closed by krzys-h** 2015-06-26 17:21 UTC
Labels: bug, graphics
