### ISSUE TITLE
Persistent SEGV crashes

### ISSUE THREAD

**Issue by Casteele72** [colobot/colobot#1521] opened 2022-05-13 15:45 UTC
OS Info:
```
$ uname --all
Linux earth 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

```
Colobot info:
`Colobot: Gold Edition 0.2.0-alpha`
(Freshly installed and compiled from GitHub.)

Error:
```
Unhandled exception occurred!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.2.0-alpha, but please verify that.

The game was in phase PHASE_SIMUL (ID=8)
Last started level was: category=missions chap=1 rank=2
==============================

Sorry for inconvenience!

```

What I was doing:
Trying to (better) learn the Colobot programming langauge by writing a library of routines for specific tasks (using a class, since there seems no easier/more proper way to do this...)

Here is the code I am working on (I cannot save it as a file and attach it here, because the game crashes when I try to compile the code or it auto-compiles when I click "OK"). I am probably even doing a lot of things wrong, but since the game crashes without any additional info, I cannot even begin to find other ways to do things.

```
extern void object::Lib01(){}

public class CLib01{
	// constants
	public int _rc=ResearchCenter;
	public int _bf=BotFactory;
	
	public int _tc=Titanium;
	public int _pc=PowerCell;
	
	public int _bb=BlackBox;
	
	public int _ss=SpaceShip;
	
	private object self;// 'this'
	private object me=search(Me);
	private object ss;
	private object rc;
	private object bf;
	
	// Ctor
	public void CLib01(object self){
		this.self=self;
		ss=search(_ss);
		rc=radar(_rc);
		bf=radar(_bf);
	}
	
	// grab
	public object _grab(object obj,float alt=0.0){
		errmode(0);int fail=0;
		if(alt==0.0){alt=5.0;}
		do{
			if(++fail>10){break;}
			if(goto(obj.position,alt,1)!=0){break;}
			turn(direction(obj.position));
		} while(grab()!=0);
		return self.load;
	}
	public object _grab(int[] type,float alt=0.0){
		object[] list;int fail=1;object obj;
		list=radarall(type);
		return _grab(list[0],alt);
	}
	public object _grab(int type,float alt=0.0){
		object item=radar(type);
		return _grab(item,alt);
	}
	
	// drop
	public object _drop(object obj,point where,float alt=0.0){
		errmode(0);int abort=0;int fail=0;
		if(alt==0.0){alt=5.0;}
		do {
			if(fail++>10){abort=-1;break;}
			if(goto(obj.position,alt,1)!=0){abort=1;break;}
			turn(direction(obj.position));
		} while(drop()!=0);
		if(abort!=0){return null;}
		return obj;
	}
	public object _drop(object obj,float alt=0.0){
		return _drop(obj,self.position,alt);
	}
	
	// research
	public bool _research(int tech,bool make=false){
		if(researched(tech)==true){return true;}
		if(canresearch(tech)==false){return false;}
		object rc;
		
		rc=radar(_rc);
		if(rc==null){
			if(make==false){
				message("No RC found");
				return false;
			}
			object tc=radar(_tc);
			if(_build(_rc,tc.position)==false){
				return false;
			}
		}
		
		// RC needs battery?
		if(rc.energyCell==null){
			_grab(_pc);
			_drop(rc);
		}
		if(rc.research(tech)==0){
			return true;
		}
		return false;//Failed!?
	}
	
	// get the bb
	public void _getbb(){
		while(self.energyCell==null){wait(1.0);}
		// Short wait to let the Grabber get out of the way
		wait(3.0);
		_grab(_bb);
		object ss=radar(_ss);
		goto(ss.position);
		drop();
	}
	
	// Returns false=fail, true=success or exists
	public bool _build(int type, point pos,float ori=0.0){
		object rb=radar(type);
		if(rb!=null){return true;}
		object tc=search(_tc,pos);
		if(tc==null){return false;}
		// Is the TC already at (or near) pos?
		if(distance2d(pos,tc.position)>1.0){
			// No, so go grab it
			_grab(tc);
			goto(pos,1);turn(direction(pos));
		}
		
		// ToDo: Finish writing this...
		
		return false;
	}
}

```

**Comment by tomangelo2** [comment] 2022-05-13 16:48
Duplicate of #981 
You need to change `private object me=search(Me);` to be defined inside constructor.

**Closed by tomangelo2** 2022-05-13 16:48 UTC

**Comment by melex750** [comment] 2022-05-13 17:13
Tested. The crash is definitely ```private object me=search(Me);``` and #981; calling a function inside the class and not inside a function will usually crash. The code in the OP also exposes a few other bugs with compiling a class... So, TODO.
