### ISSUE TITLE
Aliens Queen have bad program.

### ISSUE THREAD

**Issue by kkpksp0** [colobot/colobot#991] opened 2017-06-29 08:55 UTC
![bez tytulu](https://user-images.githubusercontent.com/29771840/27679548-5acdee08-5cb9-11e7-94a3-38bf84c0e70a.png)
(build 0.1.10)

**Comment by krzys-h** [comment] 2017-06-29 08:57
Are you sure it's 0.1.10? I think I remember fixing that bug already

**Comment by krzys-h** [comment] 2017-06-29 09:00
Actually, you are right, it's fixed but not yet released in an official build. Either use a [dev build](https://compiled.colobot.info/) or wait for the next release.
https://github.com/colobot/colobot-data/commit/6b8e28c5940d0158da84e67f69798674af03dcf1

**Comment by krzys-h** [comment] 2017-06-29 09:01
Also, duplicate of #940

**Closed by krzys-h** 2017-06-29 09:00 UTC
Labels: bug, gameplay, level files, Needs verification
