### ISSUE TITLE
Programs not paused when a bot is backing up after building.

### ISSUE THREAD

**Issue by Mrocza** [colobot/colobot#641] opened 2015-09-24 16:38 UTC
After building certain structures the bot is backing up a little. During that time it calculates variables and possibly executes some functions.
The folowing program will display two diferent messages while it should not:

    build(ResearchCenter);
    object item = radar(ResearchCenter);
    float dist = distance(position,item.position);
    message(dist);
    wait(1);
    dist = distance(position,item.position);
    message(dist);

**Comment by krzys-h** [comment] 2015-09-24 16:44
Will be fixed soon

**Comment by krzys-h** [comment] 2015-09-30 18:49
I can confirm that this reports different values, but I cannot confirm that it's caused by build() exiting too early. The values are different because the function exits as soon as brakes are enabled, but breaking takes some time. It works like that for all the functions in the game that don't slow down gracefully to increase precision (for example move does this, but goto does not), so I wouldn't consider this as a bug.

**Closed by krzys-h** 2015-09-30 18:49 UTC
Labels: bug, CBOT
