### ISSUE TITLE
Problem with launching code battle

### ISSUE THREAD

**Issue by Morkoffka** [colobot/colobot#977] opened 2017-06-17 15:07 UTC
When the code battle starts, segmentation of the faul appears. As I understand, the colobot can not load textures
![default](https://user-images.githubusercontent.com/29506045/27253979-d31b0a9a-53a8-11e7-99d4-87b78d614a27.PNG)

**Comment by krzys-h** [comment] 2017-06-17 15:27
I don't think this is caused by textures, although I'd love to know what you did to make these errors appear as they are likely related to another issue which makes flat terrain check not work.
I see you are using a player name that has some weird (Russian?) characters, could you try changing that? I think somebody was reporting that the game sometimes doesn't handle that well.

**Comment by Morkoffka** [comment] 2017-06-17 16:45
Yes, there was a default user name (in Russian "player"), I changed the player name, but the problem remained.
I also found the following line. It appears almost immediately after the attempt to run:
![default](https://user-images.githubusercontent.com/29506045/27254659-f6ef3d5c-53b6-11e7-9228-3e9ca36c04f8.PNG)

Maybe we should meet the requirement of the black window (debug)

**Comment by krzys-h** [comment] 2017-06-17 17:06
I don't think this could be the problem, it shows a deprecation warning but the old code is still there.
I see you are running the dev version, does the same happen on latest official release?

**Comment by Morkoffka** [comment] 2017-06-17 17:12
I install the last dev version, because this issue was in the last release (0.1.10), to try to figure out the problem, or suddenly in the dev version it was fixed. In the previous release (0.1.9) there was no such problem.

**Comment by DavivaD** [comment] 2017-06-30 11:14
Running on Last Dev Version:
https://pastebin.com/3yKAbqQN

Same effect is on release 0.1.10.

**Comment by Morkoffka** [comment] 2017-07-14 05:18
I build colobot and run on linux ubuntu, but problem still exists

**Comment by krzys-h** [comment] 2017-10-15 19:58
Duplicate of #1023.

**Closed by krzys-h** 2017-10-15 19:58 UTC
Labels: crash

**Comment by PatrickWELTER** [comment] 2017-10-28 18:13
> Unhandled exception occurred!
> ==============================
> SIGSEGV, segmentation fault
> ==============================
> 
> This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
> including information on what you were doing before this happened and all the information below.
> ==============================
> You are running official 0.1.10-alpha build.
> 
> The game was in phase PHASE_SIMUL (ID=7)
> Last started level was: category=missions chap=3 rank=1
> ==============================
> 
> Sorry for inconvenience!
HELLO m8s, better live love laugh Long and prosper :1st_place_medal:
