### ISSUE TITLE
PowerCell has incorrect texture and energyLevel after game load

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1409] opened 2021-04-19 17:09 UTC
![power_cell](https://user-images.githubusercontent.com/12718711/115272492-a9a89300-a168-11eb-861c-9cf518eaef41.png)

Colobot v0.1.10-alpha on Ubuntu 20.04

**Steps to reproduce**
1. Make PowerCell with energyLevel = 0
2. Grab that PowerCell
3. Save game
4. Load game
5. Run program `message(load.energyLevel)`

**Expected behavior**
1. PowerCell which grabbed has energyLevel = 0
2. Lateral surface of PowerCell has red texture

**Actual behavior**
1. PowerCell which grabbed has energyLevel = -1 (see picture)
2. Lateral surface of PowerCell has metallic texture (see picture)

I get the same incorrect texture and energyLevel if I drop PowerCell to the ground before saving the game.
I get correct texture and energyLevel if I place PowerCell in the bot's energyCell before saving the game.

**Comment by tomangelo2** [comment] 2021-04-19 17:19
Duplicate of #1068, which was fixed already.
You got outdated version of game, current up-to-date version 0.1.12 is available in Ubuntu 20.04 repositories https://packages.ubuntu.com/search?keywords=colobot&searchon=names&suite=focal&section=all

**Closed by tomangelo2** 2021-04-19 17:19 UTC
