### ISSUE TITLE
AlienWorms AI scripts randomly stops after booting the level

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#845] opened 2016-10-19 16:37 UTC
You can reproduce this in Mission 4.1 and Freemission 4.1.

Not every AlienWorm is stopped - sometimes it's just two or three of them. Every AlienWorm on those levels starts with worm02.txt AI script.

The frozen AlienWorm's program can be rebooted by using "selectinsect" cheat. After you select the AlienWorm it seems the program's working, but it's title on the program list doesn't blinking. You can also instead of rebooting the program just enter to debug editor while the program is running. And then you can see goto() is highlighted.

![schowek02](https://cloud.githubusercontent.com/assets/4019345/19527145/367fb10c-9627-11e6-818a-33da156a08eb.png)

**Comment by tomangelo2** [comment] 2016-10-19 17:19
Looks like it's problem with goto(), I can't see anything wrong with Worm code. Also errmode(1) doesn't return anything. I also noticed that goto() path renderer doesn't show anything when Worm freeze. Looks like goto cannot generate path for some reason, but it doesn't want to tell why.

**Comment by tomangelo2** [comment] 2016-11-10 12:53
Caused by same problem as #844 , so this may be assumed as duplicate of it.

**Closed by tomangelo2** 2016-11-10 12:53 UTC
Labels: bug, CBOT, gameplay
