### ISSUE TITLE
Crash while using SatCom in missions.

### ISSUE THREAD

**Issue by ivanovmv** [colobot/colobot#713] opened 2016-02-10 16:55 UTC
It seems like symptom of upcoming crash is invisible text in SatCom interface.
In "Sattelite Report" information about planet (highlighted by orange color) under headers 
-> SURFACE ... -> SUBSOIL ... ->ADDITIONAL INFORMATION is invisible
In "Program dispatched by Houston"  whole program text received and links under "Archives" (but not list markers is invisible.
After few more tries to reopen and read this content from SatCom game crashes with this error:
![sigsegv](https://cloud.githubusercontent.com/assets/12450245/12954530/2f92c482-d049-11e5-9889-b1e971051e8c.png)
Windows 10 Pro x64 @ Intel 2410M ( Intel HD 3000 GPU)
P.S.: Tell me please where i can find error logs and what kind of information i can provide to make this report more helpful.

**Comment by krzys-h** [comment] 2016-02-10 17:00
Seems to be a duplicate of #708. You were probably extremly lucky that it didn't crash immediately and only the text was missing.

**Closed by krzys-h** 2016-02-10 17:00 UTC

**Comment by krzys-h** [comment] 2016-02-10 17:02
And you seem to have crashed in the same mission as #712 - maybe something is actually wrong with the help files there that causes the issue to occur more often?

**Comment by ivanovmv** [comment] 2016-02-10 17:08
I was thinking about #708 one but it was not clear enough for me.
And yes its mission 4:1 like in #712 (don't saw this one cos only read open bug reports)
It is actually appears early in game can't tell for sure now but maybe in mission 3:3 with same symptoms.
