### ISSUE TITLE
Crazy robot on Crystalia is turning around.

### ISSUE THREAD

**Issue by kkpksp0** [colobot/colobot#990] opened 2017-06-29 08:47 UTC
![rbt](https://user-images.githubusercontent.com/29771840/27679071-cda720ea-5cb7-11e7-8f98-9b2156be453b.png)

Robot is turning around doing goto();. If battery is empty it also doing a program. You can't complete this mission. (build 0.1.10)

**Comment by krzys-h** [comment] 2017-06-29 08:49
Duplicate of #844. Workaround seems to be to use 64 bit builds instead.

**Closed by krzys-h** 2017-06-29 08:49 UTC
