### ISSUE TITLE
game terminates when copy code

### ISSUE THREAD

**Issue by gorgabal** [colobot/colobot#637] opened 2015-09-17 08:05 UTC
When you copy code in-game, it seems that the OS (Debian, in this case) interpreters this as an ctrl+c sequence, initiating termination. 
## how to reproduce:
1.  start game using 'startx colobot', (or, just launching the game without desktop-environment, I used awesomewm)
2. load a game
3. try to copy some code in the in-game editor.

**Comment by gorgabal** [comment] 2015-09-17 08:08
Could be related to #183 ,

**Comment by Erihel** [comment] 2016-03-28 12:01
Is this happening with recent dev builds? This could be a bug in freeing memory when using clipboard with SDL2 that was fixed in 9679546988ebe727800e5d82bf687438eee7611b

**Comment by krzys-h** [comment] 2017-06-03 20:25
Unable to reproduce, closing

**Closed by krzys-h** 2017-06-03 20:25 UTC
Labels: bug, Needs verification, ui
