### ISSUE TITLE
FilterOnlyLanding is not SpaceShip

### ISSUE THREAD

**Issue by AndrewTernity** [colobot/colobot#968] opened 2017-05-28 22:38 UTC
I beliave that space of SpaceShip is ok for FilterOnlyLanding.

For example. Cells are on SpaceShip:
object newCells = radar(PowerCell,0,360,0,2000,1,FilterOnlyLanding);
goto(newCells.position);
Error, can't go to object. So I'll put Cell from SpaceShip to Moon and programm will ok...

**Comment by Bhudh** [comment] 2017-05-29 08:38
It's truly. Ship isn't land, it is above land.

**Comment by tomangelo2** [comment] 2017-05-29 17:31
Couldn't reproduce that, copied program to game, robot just goes to battery just like it should.

**Comment by krzys-h** [comment] 2017-05-29 17:38
It's not FilterOnlyLanding, it's goto() being buggy when navigating on the SpaceShip, there is an issue for that somewhere. Closing as a duplicate.

**Closed** 2017-05-29 17:38 UTC
Labels: bug, CBOT, Needs verification
