### ISSUE TITLE
Bug  in programing torturament

### ISSUE THREAD

**Issue by qbus2002** [colobot/colobot#835] opened 2016-09-20 20:53 UTC
What in the hell I was doing?
===================
ok i was just playing around with official colobot gold alpha and i just wanted to complete all programming lessons. I runned program (that was already in an bot) and my game just crashed.
I just give you the console logs and I hope it will be patched.

**CONSOLE:**
[INFO]: Colobot: Gold Edition 0.1.8-alpha starting
[INFO]: Creating CApplication
[INFO]: Data path: ./data
[INFO]: Save path: C:\Users\jakub\colobot
[INFO]: Opening audio device...
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Error on parsing config file: No such node (Experimental.VSync)
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 4.5.0 NVIDIA 372.70
[INFO]: GeForce GTX 1070/PCIe/SSE2
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering available
[INFO]: Maximum anisotropy: 16
[INFO]: Multisampling supported, max samples: 32
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 4
[INFO]: Maximum texture size: 32768
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 32768
[INFO]: CDevice created successfully
[INFO]: Closing joystick
[WARN]: Failed to update locale, possibly incorect system configuration. Will fallback to classic locale.
[INFO]: Created shadow map texture: 8192x8192, depth 32
[INFO]: Reseting world on phase change...
[INFO]: Simulation speed = 1.00
[INFO]: Loading level: levels/exercises/chapter001/level005/scene.txt
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".
[WARN]: This level is using deprecated way of defining %1$s scene. Please change the %1$s= parameter in EndingFile from %2$d to "levels/other/%1$s%2$03d.txt".
[INFO]: Simulation speed = 1.00
[INFO]: Simulation speed = 1.00
[INFO]: Simulation speed = 1.00
Unhandled exception occurred!
Type: std::runtime_error
Message: Tried to access invalid particle channel (invalid ID)
This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
You seem to be running a custom compilation of version 0.1.8-alpha, but please verify that.
The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=exercises chap=1 rank=5
Sorry for inconvenience!

Screen with all of this on one screen
=============================
![image](https://cloud.githubusercontent.com/assets/12773343/18688248/c0a04460-7f83-11e6-8b7a-35885f6147da.png)

o and btw. my graphics settings looks like this
==================================
![image](https://cloud.githubusercontent.com/assets/12773343/18688318/1560ebda-7f84-11e6-9472-de977a189bd8.png)

And sorry for my english I'm half Polsih half Netherlands

**Comment by krzys-h** [comment] 2016-09-20 21:00
Duplicate of #806

**Closed by krzys-h** 2016-09-20 21:00 UTC
Labels: duplicate
