### ISSUE TITLE
Stopping program while executing build makes titanium unusable

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1414] opened 2021-05-04 18:23 UTC
Colobot v0.1.12-alpha

**Steps to reproduce**

1. Run program near the Titanium on the Grabber:
```
extern void object::BuildRadarStation_() {
    build(RadarStation);
    message("code after build");
}
```
2. Interrupt the program while build command executing.

**Expected behavior**
I think build command should be transaction.

**Incorrect behavior**
Titanium becomes unusable. I mean you can not grab it or continue building something using it. "Unusable" Titanium often looks like a normal Titanium, but if you find a moment to stop the program, you will see frozen half Titanium half RadarStation (see picture).

![nedo-radar](https://user-images.githubusercontent.com/12718711/117049859-e8c90d80-ad3e-11eb-975f-3b70fc6e9d61.png)

**Comment by tomangelo2** [comment] 2021-05-04 18:31
Duplicate of #1025

**Closed by tomangelo2** 2021-05-04 18:31 UTC
