### ISSUE TITLE
AlienQueen getting stuck after loading saved game

### ISSUE THREAD

**Issue by SandJ** [colobot/colobot#495] opened 2015-07-08 09:46 UTC
In the final mission, when a saved game is loaded, sometimes the AlienQueen gets stuck and stops laying eggs.  The attached image shows her trying to climb the hill and getting nowhere.

Version: 0.1.5-alpha
O/S: Xubuntu 14.04

![alienqueen stuck](https://cloud.githubusercontent.com/assets/3825477/8567430/30f1d2ec-255d-11e5-8cf8-12ce1ce51f6e.png)

~~I have attached a saved game.~~  "*Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG.*"  There is a saved game showing the problem here: https://www.dropbox.com/s/msuuj5jdv7tq6yg/save1507081028Terranova4.zip?dl=0

**Comment by RaptorParkowsky** [comment] 2015-07-08 13:32
Probably something wrong with simulation speed. For now, it's very risky to playing with higher speeds.

**Comment by SandJ** [comment] 2015-07-08 13:45
I'm not so sure it is down to simulation speed.

I have played this mission half a dozen times and only notice the queen ant stop producing new ants after a game restore.  I even left it running overnight at 4x speed a couple of nights ago and my defence towers were still killing ants in the morning.

Incidentally, in the saved game, if I 'nudge' the queen using the Phazer (i.e. keep pushing her), she will go back to laying eggs and wandering about.

**Comment by krzys-h** [comment] 2015-07-08 13:51
It's more probably related to #119, from what I remember this program goes through points with given coordinates in order. After reloading it loses the loop counter and tries to move to the first point again.
You can use the "selectinsect" cheat code (in console activated by pressing ~) to select the AlienQueen and see if the program is running or not. You can also open the CBot debugger to see what's going on with the loop counter.
I'll try to load this save file to check that later.

**Comment by krzys-h** [comment] 2015-07-08 18:24
Yes, that's exactly what's happening.
I'm closing this issue since it is caused by #199.

**Closed by krzys-h** 2015-07-08 18:24 UTC
Labels: bug, CBOT, gameplay, Needs verification
