### ISSUE TITLE
Problem with Goto Target2

### ISSUE THREAD

**Issue by elspru** [colobot/colobot#1279] opened 2019-10-24 03:21 UTC
Hi, the Flying Drill 1 and 2 are impossible to accomplish programmatically. 
This is a programming game, so that is a massive problem. 

The problem is that when one does a goto the Target2, then it never realizes that it has reached the target, and so it ends up just hanging there. 

And I have 0 interest in doing it non-programmatically, this is a programming game... Considering I don't know how long it will take you guys to get this fixed, is there any way I can skip this flight drill level for now? Thanks

here is my code that in theory would go from one target to the next, but it always gets stuck on the first target.  For example it never reaches the statement after the goto, which is "target acquired". Even though it does otherwise acquire the target. 

extern void object::GetTarget()
{
	
	object[] targets = radarall(Target2);
	object[] visited;
	message(sizeof(targets));
	for (int i = 0; i < sizeof(targets); ++i) {
		int closest_distance = 70000;
		object closest_target;
		int this_distance = 0;
		for (int j = 0; j < sizeof(targets); ++j) {
			boolean visit = false;
			for (int k = 0; k < sizeof(visited); ++k) {
				if (targets[j].position == visited[k].position) {
					visit = true;
					break;
				}
			}
			if (visit == true) {
				continue;
			}
			this_distance = distance(position, targets[j].position);
			if (this_distance < closest_distance) {
				closest_target = targets[i];
				closest_distance = this_distance;
			}
			
			//
			
		}
		message("closest distance " +  closest_distance);
		message("this distance " +  this_distance);
		point the_position = closest_target.position;
		message("the point " + the_position);
		message("altitude " + closest_target.altitude);
		float the_altitude = closest_target.position.z;
		message("the altitude " + the_altitude);
		goto(the_position,the_altitude,1);
		message("target acquired");
		visited[sizeof(visited)] = closest_target;
		jet(0.3);
		move(3);
	}
}

**Comment by MrSimbax** [comment] 2019-10-24 09:00
The missions are not designed to be beaten fully programmatically. The flying drills are not the last missions you will encounter with this issue as in some of them you have literally no bots so no programming option at all. You can either play them the way they were intended to play and use programming only as additional help or use cheat codes to skip such missions.

BTW It is possible to beat these particular missions with programming, it's just not as simple as a loop with `goto`. Your solution seems overcomplicated. For example, I don't know why you use `radarall` instead of just `radar`. I just beat the mission with around 20 lines of code (although it's not "as fast as possible" (and probably not the shortest program either), to obtain the optimal speed you might need to use some trigonometry, but for just beating the mission the solution is much simpler). **Hint:** check documentation for other functions related to movement. I only used `goto` to fly to the SpaceShip after I've cleared all the targets.

Note some missions may require disproportionally more work and knowledge to beat programmatically because as I said they are not designed to be a programming course. If you want programming only levels, see exercises, challenges, CodeBattles, or other Epsitec games like CeeBot.

**Comment by elspru** [comment] 2019-10-24 17:05
Well my impression is that Colobot is about colonizing with bots. Or a bot colonization emulator.
Like even Elon Musk admits that we will have to colonize Mars with robots before a single human sets foot on Mars.
So if any characters are optional I'd have to say it is the man.
Could have an android man replacement that does accept programs for the levels than don't have bots. Or simply add a bot to those levels.

The reason I used radarall is because radar often seems to get the nearest object which would be the target I just went through.

It is not clear to me how can use the move and jet commands to fly through the course, especially since getting the alignment correct seems questionable.

Maybe you'd like to share your code?

Also what are the cheat codes?

I think it is fully valid to have a goto that completes when it reaches a non ground location.

Thanks.

**Comment by tomangelo2** [comment] 2019-10-24 17:19
http://colobot.info/SatComOnline/master/cbot/radar
You can set parameters to check for targets away of 5 meters and in front of robot, this way you won't detect targets that you already passed by.

Also goto() might be not reliable enough to operate in 3D. Sometimes it doesn't even works correctly in 2D (it's already known issue). To make fully reliable code you should stick to move();, turn(); and jet(); commands. Another helpful commands would be direction(), distance() and distance2d() functions.

**Comment by MrSimbax** [comment] 2019-10-24 17:24
```cpp
extern void object::FlyingDrill()
{
    float eps = 3.0;
    float shift_xy = 5.0;
    float temp_treshold = 0.8;
    float jet_power = 0.6;
    object target = radar(Target2);
    while (target != null)
    {
        while (target.position.z - this.position.z >= eps)
            jet(jet_power);
        while (this.position.z - target.position.z >= eps)
            jet(-jet_power);
        jet(0.0);
        turn(direction(target.position));
        move(distance(this.position, target.position) + shift_xy);
        if (this.temperature >= temp_treshold)
        {
            while (this.temperature > 0.0)
                jet(-1.0);
        }
        target = radar(Target2);
    }
    
    goto(radar(SpaceShip).position);
}```

**Comment by MrSimbax** [comment] 2019-11-01 18:00
I'm closing this issue due to the author not responding and since the program above works, I assume the issue is solved.

**Closed by MrSimbax** 2019-11-01 18:00 UTC
Labels: CBOT, gameplay, question/general discussion
