### ISSUE TITLE
Bot can't feel its wheels on x8.0

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1411] opened 2021-04-29 23:36 UTC
Colobot v0.1.12-alpha, `Intel Corporation 4 Series Chipset Integrated Graphics Controller`.

**Steps to reproduce**
1. Set game speed to x8.0 or faster
2. Makes movements by WheeledGrabber.

**Incorrect behavior**

The bot wheels is not visible.

![Снимок экрана от 2021-04-24 04-20-29](https://user-images.githubusercontent.com/12718711/116630189-02ec9f80-a97d-11eb-9cea-d7b42e674ae8.png)

**Comment by pestoffne** [comment] 2021-04-30 13:09
The issue is not reproducible with `NVIDIA Corporation GK208B [GeForce GT 730]`.

**Comment by tomangelo2** [comment] 2021-05-04 18:28
Duplicate of #1164

**Closed by tomangelo2** 2021-05-04 18:28 UTC
