### ISSUE TITLE
Crash after victory scene

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#521] opened 2015-07-20 14:41 UTC
```
Assertion failed: chapter == 0, file /var/lib/jenkins/workspace/colobot-gold-mai
n-dev/src/object/level/parser.cpp, line 114

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[Inferior 1 (process 1432) exited with code 03]
(gdb) backtrace
No stack.
(gdb)
```
It happen after every mission.

**Comment by krzys-h** [comment] 2015-07-20 15:02
Which version are you using?
I'm actually getting a different crash in the most recent version:
```colobot: /home/krzys_h/Pulpit/colobot/src/common/restext.cpp:811: const char* GetResourceBase(ResType, unsigned int): Warunek zapewnienia `num < RT_MAX' nie został spełniony.```

**Comment by krzys-h** [comment] 2015-07-20 15:07
My crash is fixed in 572b8ea5662be1ecb7fd130a843fe9c38dee3c4a, I can't reproduce your one.

**Comment by tomangelo2** [comment] 2015-07-20 15:31
It was in today release build.

**Comment by RaptorParkowsky** [comment] 2015-07-20 17:43
I can confirm that on today's debug build.

**Comment by krzys-h** [comment] 2015-07-20 17:46
Does it really happen after every win scene? I've checked all win scenes in  chapters 1 and 2 and they all work fine for me.

**Comment by krzys-h** [comment] 2015-07-20 17:47
Also, there were multiple builds today, I need to know if this is before or after 572b8ea5662be1ecb7fd130a843fe9c38dee3c4a

**Comment by RaptorParkowsky** [comment] 2015-07-20 17:52
Yes, that happens always after win scenes in first missions on Earth and Exercises. That happened on git-HEAD~rlc947f9 (or git-HEAD~r**1**c947f9, I can't just paste it from game menu).

**Comment by krzys-h** [comment] 2015-07-20 18:01
This is the release build from midnight, that was definetly before the commit I asked about :P
I'm asking about the debug build because you said it happened there. Unless the build bot broke...

**Comment by Erihel** [comment] 2015-07-20 19:11
Can't reproduce it with newest version.

**Comment by RaptorParkowsky** [comment] 2015-07-21 08:52
I can confirm that in newest git-HEAD~r72b9738. I think this issue can be closed now.

**Closed by RaptorParkowsky** 2015-07-21 08:52 UTC
Labels: bug
