### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LogicalKip** [colobot/colobot#712] opened 2016-02-07 10:20 UTC
The game crashed soon after the beginning of mission 4:1, I think I had just pressed F1.
I was playing the latest stable release (0.1.6-alpha) from the website installer, on Windows 10.

![crash](https://cloud.githubusercontent.com/assets/2334026/12871797/21ef95b8-cd8c-11e5-94a3-0e6f1c592289.png)

**Comment by krzys-h** [comment] 2016-02-07 11:27
Probably duplicate of #708

**Closed** 2016-02-07 11:27 UTC
