### ISSUE TITLE
Game unplayable and UI scramble in code battles

### ISSUE THREAD

**Issue by Mrocza** [colobot/colobot#761] opened 2016-04-05 19:37 UTC
![issue 1](https://cloud.githubusercontent.com/assets/1828157/14295424/d08bb6ee-fb75-11e5-9b30-ab4d10f6486a.png)

Way to reproduce:
1. Run the game in windowed mode.
2. Start any code battle level.
3. Open code editor.
4. Resize the window.
5. Hit the "start battle" button.

**Comment by Emxx52** [comment] 2021-09-29 22:31
Cannot reproduce, closing

**Closed by Emxx52** 2021-09-29 22:31 UTC
Labels: bug, ui
