### ISSUE TITLE
SIGSEGV when trying to start code battle

### ISSUE THREAD

**Issue by Tungstene** [colobot/colobot#1034] opened 2017-10-13 10:19 UTC
![colobot-codebattle-bug](https://user-images.githubusercontent.com/17686032/31541778-149bd292-b010-11e7-9c74-e2f7af2bf294.png)

SIGSEGV crashes with 32bit and 64bit Windows versions of the software (alpha or dev), whichever chapter I choose. It occurs at the end of the loading phase (as far as I can see). Dev console last messages shows it is loading some file (not the same at each try).

Programing category works fine, though.

**Comment by DavivaD** [comment] 2017-10-13 10:36
Related to #1023
Duplicate of #977

**Comment by krzys-h** [comment] 2017-10-15 19:58
Duplicate of #1023.

**Closed by krzys-h** 2017-10-15 19:58 UTC
