### ISSUE TITLE
Probable start/finish platform issue.

### ISSUE THREAD

**Issue by Quartofel** [colobot/colobot#878] opened 2016-12-24 18:44 UTC
I've came back to the Colobot recently and I'm doing the campaign once again, this time I've wanted to do it almost exclusively with bots thanks to the new possibilities.
But during the final mission on Earth I've found that my program...
`extern void object::bbox01()
{
	object box;  
	object ship;  
	box = radar(BlackBox);  
	goto(box.position);  
	grab();  
	ship = radar(SpaceShip);  
	goto(ship.position);  
	drop();  
}
`
...is generating error saying that location is blocked while doing _goto(box.position);_. I think that for some reason program thinks that start (or finish, I don't know which one is placed there) platform, on which Black Box is placed is the reason of the error.
It's almost exact copy of the program I've used as a kid, and then it worked perfectly.

**Comment by krzys-h** [comment] 2016-12-24 19:27
This is already fixed in the latest development version. eb2a1857dc9db7ded613027045c4e78781ec1bca
Duplicate of #732

**Closed** 2016-12-24 19:27 UTC
Labels: CBOT

**Comment by krzys-h** [comment] 2016-12-24 19:28
You can find development versions at https://compiled.colobot.info ;)

**Comment by Quartofel** [comment] 2016-12-24 19:38
I am terribly sorry for repost then.

**Comment by tomangelo2** [comment] 2016-12-24 21:14
I was sure that there was issue like this, but I couldn't find it.
