### ISSUE TITLE
Clicking the area where start battle button would be crashes game in CBOT editor.

### ISSUE THREAD

**Issue by melex750** [colobot/colobot#670] opened 2015-10-23 01:47 UTC
This is after starting a code battle mission.
The start battle button appears and all buttons in the interface lose their functionality.
The keyboard still works after that.  You can still move and resize the editor window
but the buttons and the text field do not move with it.

version 0.1.6-alpha compiled locally unmodified.
OS: Xubuntu x86_64

**Comment by melex750** [comment] 2015-10-31 11:39
This appears to be related.

The start code battle button appears at the main menu screen
after aborting a code battle,  then changing the screen resolution.

Clicking on it crashes the game.

It does not happen if you already started the battle.

**Comment by krzys-h** [comment] 2015-10-31 14:00
This is caused by resizing the window and recreating the interface to fix aspect ratio

**Comment by RaptorParkowsky** [comment] 2015-11-01 09:54
@krzys-h Are you sure this will be fixed in 0.1.7? This probably require CEGUI refactoring I think...

**Comment by krzys-h** [comment] 2015-11-01 12:26
We can add some dirty workaround, but yes the proper fix would be CEGUI implementation.
I want to fix it just because it crashes the whole game, other UI issues can wait.

**Comment by piotrdz** [comment] 2015-11-10 20:41
Thanks to @piotrwalkusz1, it seems to be fixed now.

**Closed by piotrdz** 2015-11-10 20:41 UTC
Labels: bug, ui
